// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DictionRecordItem.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - DictionRecordItemRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface DictionRecordItemRoot : GPBRootObject
@end

#pragma mark - DictationRecordItem

typedef GPB_ENUM(DictationRecordItem_FieldNumber) {
  DictationRecordItem_FieldNumber_Type = 1,
  DictationRecordItem_FieldNumber_Date = 2,
  DictationRecordItem_FieldNumber_LastModify = 3,
  DictationRecordItem_FieldNumber_SampleCount = 4,
};

@interface DictationRecordItem : GPBMessage

/// 0:写作 1：随笔 2：采访
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
/// 录音日期
@property(nonatomic, readwrite) int64_t date;

@property(nonatomic, readwrite) BOOL hasDate;
/// 最近一次修改时间,客户端据修改时间排序
@property(nonatomic, readwrite) int64_t lastModify;

@property(nonatomic, readwrite) BOOL hasLastModify;
/// 录音长度
@property(nonatomic, readwrite) int64_t sampleCount;

@property(nonatomic, readwrite) BOOL hasSampleCount;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
